# ---
# # Ingress-TLS-Secret
# apiVersion: v1
# kind: Secret
# metadata:
#     name: example-tls
#     namespace: foo
# data:
#     tls.crt: <base64 encoded cert>
#     tls.key: <base64 encoded key>
# type: kubernetes.io/tls
---
# CONFIGMAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: wpconfigmap
  namespace: production
data:
  isok: "wpisready"
---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  namespace: production
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: default